
package service.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.Client;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface ClientService {


    /**
     * 
     * @return
     *     returns java.util.List<types.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfClients", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetListOfClients")
    @ResponseWrapper(localName = "getListOfClientsResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetListOfClientsResponse")
    @Action(input = "http://endpoint.service/ClientService/getListOfClientsRequest", output = "http://endpoint.service/ClientService/getListOfClientsResponse")
    public List<Client> getListOfClients();

}
