
package service.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.Client;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface ClientService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findClientByNumberPhone", targetNamespace = "http://endpoint.service/", className = "service.endpoint.FindClientByNumberPhone")
    @ResponseWrapper(localName = "findClientByNumberPhoneResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.FindClientByNumberPhoneResponse")
    @Action(input = "http://endpoint.service/ClientService/findClientByNumberPhoneRequest", output = "http://endpoint.service/ClientService/findClientByNumberPhoneResponse")
    public Long findClientByNumberPhone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClient", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteClient")
    @ResponseWrapper(localName = "deleteClientResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteClientResponse")
    @Action(input = "http://endpoint.service/ClientService/deleteClientRequest", output = "http://endpoint.service/ClientService/deleteClientResponse")
    public void deleteClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://endpoint.service/", className = "service.endpoint.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.UpdateClientResponse")
    @Action(input = "http://endpoint.service/ClientService/updateClientRequest", output = "http://endpoint.service/ClientService/updateClientResponse")
    public void updateClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

    /**
     * 
     * @return
     *     returns java.util.List<types.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfClients", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetListOfClients")
    @ResponseWrapper(localName = "getListOfClientsResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetListOfClientsResponse")
    @Action(input = "http://endpoint.service/ClientService/getListOfClientsRequest", output = "http://endpoint.service/ClientService/getListOfClientsResponse")
    public List<Client> getListOfClients();

}
