<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <form action="/signup" method="post">
        <input name="firstName" placeholder="Имя">
        <input name="middleName" placeholder="Отчество">
        <input name="secondName" placeholder="Фамилия">
        <input type="submit" value="Зарегистрироваться">
    </form>
</div>
</body>
</html>